services:
  db:
    image: postgres:15
    container_name: proyecto_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/01-DDL.sql:/docker-entrypoint-initdb.d/01-DDL.sql
      - ./db/02-inserts.sql:/docker-entrypoint-initdb.d/02-inserts.sql

volumes:
  db_data: